#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <variant>
#include <vector>
using namespace std;
int main(){ios::sync_with_stdio(false);cin.tie(nullptr);int n;long long k;if(!(cin>>n>>k))return 0;vector<long long> p(n+1);for(int i=1,x;i<=n;i++){cin>>x;p[i]=p[i-1]+x;}deque<int> dq;int ans=n+1;for(int i=0;i<=n;i++){while(!dq.empty()&&p[i]-p[dq.front()]>=k){ans=min(ans,i-dq.front());dq.pop_front();}while(!dq.empty()&&p[i]<=p[dq.back()])dq.pop_back();dq.push_back(i);}cout<<(ans==n+1?-1:ans)<<endl;}