#include<stdio.h>
#include<string.h>
int main(void){
    int a,b,c,d,e,f,g,h,i,j,k;
    char t[30];
    scanf("%s",t);
    a=t[0]-'0';
    b=t[2]-'0';
    c=t[3]-'0';
    d=t[4]-'0';
    e=t[6]-'0';
    f=t[7]-'0';
    g=t[8]-'0';
    h=t[9]-'0';
    i=t[10]-'0';
    j=(a+2*b+3*c+4*d+5*e+6*f+7*g+8*h+9*i)%11;
    if(j==10){
        if(t[12]=='X'){
            printf("Right\n");
        }
        else{
            t[12]='X';
            puts(t);
        }
    }
    if(j==9){
        if(t[12]=='9'){
            printf("Right\n");
        }
        else{
            t[12]='9';
            puts(t);
        }
    }
    if(j==8){
        if(t[12]=='8'){
            printf("Right\n");
        }
        else{
            t[12]='8';
            puts(t);
        }
    }   
    if(j==7){
        if(t[12]=='7'){
            printf("Right\n");
        }
        else{
            t[12]='7';
            puts(t);
        }   
    }
    if(j==6){
        if(t[12]=='6'){
            printf("Right\n");
        }
        else{
            t[12]='6';
            puts(t);
        }
    }
    if(j==5){
        if(t[12]=='5'){
            printf("Right\n");
        }
        else{
            t[12]='5';
            puts(t);
        }   
    }
    if(j==4){
        if(t[12]=='4'){
            printf("Right\n");
        }
        else{
            t[12]='4';
            puts(t);
        }
    }
    if(j==3){
        if(t[12]=='3'){
            printf("Right\n");
        }
        else{
            t[12]='3';
            puts(t);
        }   
    }
    if(j==2){
        if(t[12]=='2'){
            printf("Right\n");
        }
        else{
            t[12]='2';
            puts(t);
        }   
    }
    if(j==1){
        if(t[12]=='1'){
            printf("Right\n");
        }
        else{
            t[12]='1';
            puts(t);
        }   
    }
    if(j==0){
        if(t[12]=='0'){
            printf("Right\n");
        }
        else{
            t[12]='0';
            puts(t);
        }   
    }
    return 0;
}