#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <variant>
#include <vector>
using namespace std;struct DSU{vector<int>p,d;DSU(int n):p(n+1),d(n+1,0){iota(p.begin(),p.end(),0);}int find(int x){if(p[x]==x)return x;int y=p[x],r=find(y);d[x]=(d[x]+d[y])%3;return p[x]=r;}bool add(int typ,int x,int y){int rx=find(x),ry=find(y),rel=(typ==1?0:1);if(rx==ry)return (d[x]-d[y]+3)%3==rel; p[rx]=ry;d[rx]=(rel+d[y]-d[x]+3)%3;return true;}};int main(){ios::sync_with_stdio(false);cin.tie(nullptr);int n,k;if(!(cin>>n>>k))return 0;DSU u(n);int bad=0;for(int i=0,D,x,y;i<k;i++){cin>>D>>x>>y;if(x<1||x>n||y<1||y>n|| (D==2&&x==y) || (D!=1&&D!=2)){bad++;continue;}if(!u.add(D,x,y))bad++;}cout<<bad<<endl;return 0;}