#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <variant>
#include <vector>
using namespace std;
int main(){ios::sync_with_stdio(false);cin.tie(nullptr);int n;if(!(cin>>n))return 0;vector<long long>a(n),ord;for(auto&x:a)cin>>x;long long key;cin>>key;function<void(int)>dfs=[&](int u){if(u>=n)return;dfs(2*u+1);ord.push_back(a[u]);dfs(2*u+2);};dfs(0);int pos=find(ord.begin(),ord.end(),key)-ord.begin();long long pre=pos>0?ord[pos-1]:-1,suc=pos+1<(int)ord.size()?ord[pos+1]:-1;cout<<pre<<' '<<suc<<endl;return 0;}