#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <variant>
#include <vector>
using namespace std;
int main(){ios::sync_with_stdio(false);cin.tie(nullptr);string s;if(!(cin>>s))return 0;vector<string> out;vector<char> ops;auto prec=[](char c){return c=='+'?1:2;};for(int i=0;i<(int)s.size();){char c=s[i];if(isdigit((unsigned char)c)){int j=i;while(j<(int)s.size()&&isdigit((unsigned char)s[j]))j++;out.push_back(s.substr(i,j-i));i=j;}else if(c=='('){ops.push_back(c);i++;}else if(c==')'){while(!ops.empty()&&ops.back()!='('){out.push_back(string(1,ops.back()));ops.pop_back();}if(!ops.empty())ops.pop_back();i++;}else if(c=='+'||c=='*'){while(!ops.empty()&&ops.back()!='('&&prec(ops.back())>=prec(c)){out.push_back(string(1,ops.back()));ops.pop_back();}ops.push_back(c);i++;}else if(c=='@'){break;}else i++;}while(!ops.empty()){if(ops.back()!='(')out.push_back(string(1,ops.back()));ops.pop_back();}for(int i=0;i<(int)out.size();i++){if(i)cout<<' ';cout<<out[i];}cout<<endl;vector<long long> st;for(string &t:out){if(isdigit((unsigned char)t[0]))st.push_back(stoll(t));else{long long b=st.back();st.pop_back();long long a=st.back();st.pop_back();st.push_back(t[0]=='+'?a+b:a*b);}}cout<<st.back()<<endl;return 0;}