#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <variant>
#include <vector>
using namespace std;
int main(){ios::sync_with_stdio(false);cin.tie(nullptr);int n,m;if(!(cin>>n>>m))return 0;vector<vector<pair<int,long double>>> g(n+1);for(int i=0,u,v;i<m;i++){unsigned long long w;cin>>u>>v>>w;g[u].push_back({v,log((long double)w)});}const long double INF=1e100L;vector<long double>d(n+1,INF);vector<int>pre(n+1,-1);priority_queue<pair<long double,int>,vector<pair<long double,int>>,greater<pair<long double,int>>>q;d[1]=0;q.push({0,1});while(!q.empty()){auto [du,u]=q.top();q.pop();if(du>d[u])continue;for(auto [v,w]:g[u]){long double nd=du+w;if(nd<d[v]){d[v]=nd;pre[v]=u;q.push({nd,v});}}}for(int i=2;i<=n;i++){if(i>2)cout<<' ';cout<<pre[i];}cout<<endl;return 0;}