#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <variant>
#include <vector>
using namespace std;
vector<string> t; int at=0; long long ans=0;
long long go(){string s=t[at++]; if(s=="#") return 0; long long v=stoll(s),l=go(),r=go(); ans=max(ans,v+max(0LL,l)+max(0LL,r)); return v+max(0LL,max(l,r));}
int main(){ios::sync_with_stdio(false);cin.tie(nullptr);string s;if(!(cin>>s))return 0;string u;for(char c:s){if(c==','){t.push_back(u);u.clear();}else u.push_back(c);}if(!u.empty())t.push_back(u);go();cout<<ans<<endl;return 0;}