#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <variant>
#include <vector>
using namespace std;
int main(){ios::sync_with_stdio(false);cin.tie(nullptr);int n;long long m;if(!(cin>>n>>m))return 0;vector<long long> h(n);long long hi=0;for(auto&v:h){cin>>v;hi=max(hi,v);}long long lo=0;while(lo<hi){long long mid=(lo+hi+1)/2;long long got=0;for(long long v:h)if(v>mid){got+=v-mid;if(got>=m)break;}if(got>=m)lo=mid;else hi=mid-1;}cout<<lo<<endl;return 0;}