name = "ruc-yoj-traffic"
main = "src/index.js"
compatibility_date = "2026-09-21"

[vars]
ALLOWED_ORIGIN = "https://scorpascal.github.io"

[[d1_databases]]
binding = "DB"
database_name = "ruc-yoj-traffic"
database_id = "5a5ef10f-2de3-4eaf-a3de-48543c497f10"
