#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <variant>
#include <vector>
using namespace std;struct BIT{int n;vector<long long>b;BIT(int n=0):n(n),b(n+2){}void add(int x,long long v){for(;x<=n;x+=x&-x)b[x]+=v;}long long sum(int x){long long r=0;for(;x;x-=x&-x)r+=b[x];return r;}};int main(){ios::sync_with_stdio(false);cin.tie(nullptr);int n,q;if(!(cin>>n>>q))return 0;vector<vector<int>>ch(n+1);for(int i=2,p;i<=n;i++){cin>>p;ch[p].push_back(i);}vector<int>tin(n+1),tout(n+1),it(n+1),st;int timer=0;st.push_back(1);while(!st.empty()){int u=st.back();if(!tin[u])tin[u]=++timer;if(it[u]<(int)ch[u].size())st.push_back(ch[u][it[u]++]);else{tout[u]=timer;st.pop_back();}}BIT bit(n+2);while(q--){char op;cin>>op;if(op=='a'){int x;long long v;cin>>x>>v;bit.add(tin[x],v);bit.add(tout[x]+1,-v);}else if(op=='q'){int x;cin>>x;cout<<bit.sum(tin[x])<<endl;}}return 0;}