#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <variant>
#include <vector>
using namespace std;
int main(){ios::sync_with_stdio(false);cin.tie(nullptr);string s,t;int K;if(!(cin>>s>>t>>K))return 0;int n=s.size(),m=t.size();size_t W=(size_t)(n+1)*(m+1);vector<int>dp((size_t)(K+1)*W,0);auto id=[&](int k,int i,int j){return (size_t)k*W+(size_t)i*(m+1)+j;};for(int k=0;k<=K;k++)for(int i=1;i<=n;i++)for(int j=1;j<=m;j++){int v=max(dp[id(k,i-1,j)],dp[id(k,i,j-1)]);if(s[i-1]==t[j-1])v=max(v,dp[id(k,i-1,j-1)]+1);else if(k>0)v=max(v,dp[id(k-1,i-1,j-1)]+1);dp[id(k,i,j)]=v;}cout<<dp[id(K,n,m)]<<endl;return 0;}