#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <variant>
#include <vector>
using namespace std;struct Node{int v,dist;Node*l,*r;Node(int x):v(x),dist(1),l(nullptr),r(nullptr){}};int dn(Node*x){return x?x->dist:0;}Node* mergeH(Node*a,Node*b){if(!a)return b;if(!b)return a;if(a->v>b->v)swap(a,b);a->r=mergeH(a->r,b);if(dn(a->l)<dn(a->r))swap(a->l,a->r);a->dist=dn(a->r)+1;return a;}int main(){ios::sync_with_stdio(false);cin.tie(nullptr);int n,m;if(!(cin>>n))return 0;Node*A=nullptr;for(int i=0,x;i<n;i++){cin>>x;A=mergeH(A,new Node(x));}cin>>m;Node*B=nullptr;for(int i=0,x;i<m;i++){cin>>x;B=mergeH(B,new Node(x));}A=mergeH(A,B);cout<<dn(A)<<endl;bool first=true;while(A){if(!first)cout<<' ';first=false;cout<<A->v;A=mergeH(A->l,A->r);}cout<<endl;return 0;}