#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <variant>
#include <vector>
using namespace std;
void printv(const vector<long long>&v){for(int i=0;i<(int)v.size();i++){if(i)cout<<' ';cout<<v[i];}cout<<endl;}int main(){ios::sync_with_stdio(false);cin.tie(nullptr);int n;if(!(cin>>n))return 0;vector<long long>a(n);for(auto&x:a)cin>>x;vector<long long>pre,in,post;stack<int> st;st.push(0);while(!st.empty()){int u=st.top();st.pop();if(u>=n)continue;pre.push_back(a[u]);st.push(2*u+2);st.push(2*u+1);}int cur=0;while(cur<n||!st.empty()){while(cur<n){st.push(cur);cur=2*cur+1;}cur=st.top();st.pop();in.push_back(a[cur]);cur=2*cur+2;}stack<int>s1,s2;s1.push(0);while(!s1.empty()){int u=s1.top();s1.pop();if(u>=n)continue;s2.push(u);s1.push(2*u+1);s1.push(2*u+2);}while(!s2.empty()){post.push_back(a[s2.top()]);s2.pop();}printv(pre);printv(in);printv(post);return 0;}