#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <chrono>
#include <climits>
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <queue>
#include <random>
#include <regex>
#include <set>
#include <sstream>
#include <stack>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <variant>
#include <vector>
using namespace std;void ms(vector<int>&a,vector<int>&t,int l,int r){if(r-l<2)return;int m=(l+r)/2;ms(a,t,l,m);ms(a,t,m,r);int i=l,j=m,k=l;while(i<m||j<r)t[k++]=(j==r||(i<m&&a[i]<=a[j]))?a[i++]:a[j++];for(i=l;i<r;++i)a[i]=t[i];}int main(){int n;cin>>n;vector<int>a(n),t(n);for(int&x:a)cin>>x;ms(a,t,0,n);for(int i=0;i<n;++i){if(i)cout<<' ';cout<<a[i];}cout<<endl;}